name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            name: "amd64"
          - platform: "linux/arm64"
            name: "arm64"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: echo ${{ github.ref }} | grep $(make version)

      - name: Build and Export Linux Binaries
        run: docker buildx build --platform=${{ matrix.platform }} --output=. .

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-linux-binaries
          path: '*.tar.gz'

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make release
        run: FAT_BINARY=true make release

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: '*.zip'

  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - run: find .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            amd64-linux-binaries/*.tar.gz
            arm64-linux-binaries/*.tar.gz
            macos-binaries/*.zip
          prerelease: false
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
